#sh scripts/test_ctpt.sh Pets 4
#sh scripts/test_ctpt.sh DTD 4
#sh scripts/test_ctpt.sh Flower102 4
#sh scripts/test_ctpt.sh Caltech101 4
#sh scripts/test_ctpt.sh Aircraft 4
#sh scripts/test_ctpt.sh UCF101 4
#sh scripts/test_ctpt.sh Cars 5
#sh scripts/test_ctpt.sh eurosat 4
#sh scripts/test_ctpt.sh SUN397 4
#sh scripts/test_ctpt.sh Food101 4
#sh scripts/test_ctpt.sh I 0

#sh scripts/test_ctpt_constr.sh Pets 3
#sh scripts/test_ctpt_constr.sh DTD 3
#sh scripts/test_ctpt_constr.sh Flower102 3
#sh scripts/test_ctpt_constr.sh Caltech101 3
#sh scripts/test_ctpt_constr.sh Aircraft 3
#sh scripts/test_ctpt_constr.sh UCF101 3
#sh scripts/test_ctpt_constr.sh Cars 4
#sh scripts/test_ctpt_constr.sh Food101 4
#sh scripts/test_ctpt_constr.sh eurosat 4
#sh scripts/test_ctpt_constr.sh SUN397 4
#sh scripts/test_ctpt_constr.sh I 5

#sh scripts/test_ctpt_norm.sh Pets 3
#sh scripts/test_ctpt_norm.sh DTD 3
#sh scripts/test_ctpt_norm.sh Flower102 3
#sh scripts/test_ctpt_norm.sh Caltech101 3
#sh scripts/test_ctpt_norm.sh Aircraft 3
#sh scripts/test_ctpt_norm.sh UCF101 3
#sh scripts/test_ctpt_norm.sh Cars 3
#sh scripts/test_ctpt_norm.sh Food101 4
#sh scripts/test_ctpt_norm.sh eurosat 4
#sh scripts/test_ctpt_norm.sh SUN397 4
#sh scripts/test_ctpt_norm.sh I 0

#sh scripts/test_tpt_norm.sh Pets 3
#sh scripts/test_tpt_norm.sh DTD 3
#sh scripts/test_tpt_norm.sh Flower102 3
#sh scripts/test_tpt_norm.sh Caltech101 3
#sh scripts/test_tpt_norm.sh Aircraft 3
#sh scripts/test_tpt_norm.sh UCF101 3
#sh scripts/test_tpt_norm.sh Cars 4
#sh scripts/test_tpt_norm.sh Food101 4
#sh scripts/test_tpt_norm.sh eurosat 4
#sh scripts/test_tpt_norm.sh SUN397 4

#sh scripts/test_tpt_constr.sh Pets 3
#sh scripts/test_tpt_constr.sh DTD 3
#sh scripts/test_tpt_constr.sh Flower102 3
#sh scripts/test_tpt_constr.sh Caltech101 3
#sh scripts/test_tpt_constr.sh Aircraft 3
#sh scripts/test_tpt_constr.sh UCF101 3
#sh scripts/test_tpt_constr.sh Cars 3
#sh scripts/test_tpt_constr.sh Food101 4
#sh scripts/test_tpt_constr.sh eurosat 4
#sh scripts/test_tpt_constr.sh SUN397 4
#sh scripts/test_tpt_constr.sh I 0